### ISSUE TITLE
ico interest exception

### ISSUE THREAD

**Issue by j2ther** [TheGameFreak666/iConomy-7#7]
```
[20:43:57 WARN]: Exception in thread "Timer-0"
[20:43:57 WARN]: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[20:43:57 WARN]:        at com.iCo6.system.Interest.run(Interest.java:31)
[20:43:57 WARN]:        at java.util.TimerThread.mainLoop(Timer.java:555)
[20:43:57 WARN]:        at java.util.TimerThread.run(Timer.java:505)
```

iconomy 7.0.6
spigot version git-Spigot-90f61bc-5e5cf84 (MC: 1.10.2)

**Comment by xJonathanLEI** [comment]
+1. Got this problem with the interest feature.
I guess it's trying to distribute interest payments

**Comment by Sabishi1985** [comment]
+1 The error still exists. ._. version 1.11
